version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

executors:
  default:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
        environment:
          RAILS_ENV: test

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

jobs:
  rails_minitest:
    executor:
      name: default
    steps:
      - setup

      # For speed up be precompiled
      - restore_cache:
          keys:
            - asset-cache-{{ arch }}-{{ .Branch }}
            - asset-cache-
      - run: bundle exec rails assets:precompile
      - save_cache:
          key: asset-cache-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - public/assets
            - public/packs
            - tmp/cache/assets/sprockets

      - run:
          name: Database setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate
      - run:
          name: Rails Minitest
          command: |
            bundle exec rails test
            bundle exec rails test:system

  deploy:  
    executor:
      name: default  
    steps:  
      - checkout  
      - setup  
      - add_ssh_keys:  
          fingerprints:  
            - 07:53:2f:d5:58:16:be:34:b4:49:f6:4b:5a:e0:47:e4
      - deploy:  
          name: Deploy with Capistrano  
          command: bundle exec cap production deploy 

workflows:
  test_and_deploy:
    jobs:
      - rails_minitest
      - deploy:
          requires:
            - test 
