version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

executors:
  default:
    parallelism: 3 
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
      - image: circleci/postgres:9.5-alpine 
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: books_app_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci
      PGPASSWORD: ""
      RAILS_ENV: test

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

jobs:
  rails_minitest:
    executor:
      name: default
    steps:
      - setup

      # For speed up be precompiled
      - restore_cache:
          keys:
            - asset-cache-{{ arch }}-{{ .Branch }}
            - asset-cache-
      - run: bundle exec rails assets:precompile
      - save_cache:
          key: asset-cache-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - public/assets
            - public/packs
            - tmp/cache/assets/sprockets

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Rails Minitest
          command: |
            bundle exec rails test
            bundle exec rails test:system

  deploy:  
    executor:
      name: default  
    steps:  
      - setup  
      - add_ssh_keys:  
          fingerprints:  
            - 40:5b:bb:e5:44:e1:00:48:fa:9a:7a:32:20:33:7c:3b
      - deploy:  
          name: Deploy with Capistrano  
          command: bundle exec cap production deploy 

workflows:
  test_and_deploy:
    jobs:
      - rails_minitest
      - deploy:
          requires:
            - rails_minitest 
          filters:  
            branches:  
              only: master 
